version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - KUBECONFIG=/root/.kube/config
      - CORS_ORIGIN=http://localhost:3000
      - METRICS_REFRESH_INTERVAL=5s
      - LOG_LEVEL=info
    volumes:
      - ~/.kube/config:/root/.kube/config:ro
    restart: unless-stopped
    networks:
      - k8s-dashboard

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - REACT_APP_API_URL="http://localhost:8080"
      - REACT_APP_WS_URL="ws://localhost:8080"
      - REACT_APP_REFRESH_INTERVAL=5000
      - REACT_APP_GITHUB_URL="https://github.com/Jdavid77/home-cluster"
      - REACT_APP_LINKEDIN_URL="https://www.linkedin.com/in/joaodavid77"
      - REACT_APP_INFRA_OS=K3s
      - REACT_APP_INFRA_STORAGE=Ceph
      - REACT_APP_INFRA_CNI=Cilium
      - REACT_APP_INFRA_LOAD_BALANCER=Traefik
      - REACT_APP_INFRA_GITOPS=FluxCD
      - REACT_APP_LOGO_URL="https://avatars.githubusercontent.com/u/49655819?v=4"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - k8s-dashboard

networks:
  k8s-dashboard:
    driver: bridge
